/*
 * Copyright (c) 2019 Martin Rödel a.k.a. Yomin Nimoy
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "errno.h"
#include <stddef.h>

#define CASE_STRERRNO(err) case err: return #err;

const char *strerrno(int err)
{
    switch(err)
    {
    CASE_STRERRNO(E2BIG)
    CASE_STRERRNO(EACCES)
    CASE_STRERRNO(EADDRINUSE)
    CASE_STRERRNO(EADDRNOTAVAIL)
    CASE_STRERRNO(EAFNOSUPPORT)
    CASE_STRERRNO(EAGAIN)
    CASE_STRERRNO(EALREADY)
    CASE_STRERRNO(EBADE)
    CASE_STRERRNO(EBADFD)
    CASE_STRERRNO(EBADMSG)
    CASE_STRERRNO(EBADR)
    CASE_STRERRNO(EBADRQC)
    CASE_STRERRNO(EBADSLT)
    CASE_STRERRNO(EBUSY)
    CASE_STRERRNO(ECANCELED)
    CASE_STRERRNO(ECHILD)
    CASE_STRERRNO(ECHRNG)
    CASE_STRERRNO(ECOMM)
    CASE_STRERRNO(ECONNABORTED)
    CASE_STRERRNO(ECONNREFUSED)
    CASE_STRERRNO(ECONNRESET)
    CASE_STRERRNO(EDEADLK)
    CASE_STRERRNO(EDESTADDRREQ)
    CASE_STRERRNO(EDOM)
    CASE_STRERRNO(EDQUOT)
    CASE_STRERRNO(EEXIST)
    CASE_STRERRNO(EFAULT)
    CASE_STRERRNO(EFBIG)
    CASE_STRERRNO(EHOSTDOWN)
    CASE_STRERRNO(EHOSTUNREACH)
    CASE_STRERRNO(EHWPOISON)
    CASE_STRERRNO(EIDRM)
    CASE_STRERRNO(EILSEQ)
    CASE_STRERRNO(EINPROGRESS)
    CASE_STRERRNO(EINTR)
    CASE_STRERRNO(EINVAL)
    CASE_STRERRNO(EIO)
    CASE_STRERRNO(EISCONN)
    CASE_STRERRNO(EISDIR)
    CASE_STRERRNO(EISNAM)
    CASE_STRERRNO(EKEYEXPIRED)
    CASE_STRERRNO(EKEYREJECTED)
    CASE_STRERRNO(EKEYREVOKED)
    CASE_STRERRNO(EL2HLT)
    CASE_STRERRNO(EL2NSYNC)
    CASE_STRERRNO(EL3HLT)
    CASE_STRERRNO(EL3RST)
    CASE_STRERRNO(ELIBACC)
    CASE_STRERRNO(ELIBBAD)
    CASE_STRERRNO(ELIBMAX)
    CASE_STRERRNO(ELIBSCN)
    CASE_STRERRNO(ELIBEXEC)
    CASE_STRERRNO(ELNRNG)
    CASE_STRERRNO(ELOOP)
    CASE_STRERRNO(EMEDIUMTYPE)
    CASE_STRERRNO(EMFILE)
    CASE_STRERRNO(EMLINK)
    CASE_STRERRNO(EMSGSIZE)
    CASE_STRERRNO(EMULTIHOP)
    CASE_STRERRNO(ENAMETOOLONG)
    CASE_STRERRNO(ENETDOWN)
    CASE_STRERRNO(ENETRESET)
    CASE_STRERRNO(ENETUNREACH)
    CASE_STRERRNO(ENFILE)
    CASE_STRERRNO(ENOANO)
    CASE_STRERRNO(ENOBUFS)
    CASE_STRERRNO(ENODATA)
    CASE_STRERRNO(ENODEV)
    CASE_STRERRNO(ENOENT)
    CASE_STRERRNO(ENOEXEC)
    CASE_STRERRNO(ENOKEY)
    CASE_STRERRNO(ENOLCK)
    CASE_STRERRNO(ENOLINK)
    CASE_STRERRNO(ENOMEDIUM)
    CASE_STRERRNO(ENOMEM)
    CASE_STRERRNO(ENOMSG)
    CASE_STRERRNO(ENONET)
    CASE_STRERRNO(ENOPKG)
    CASE_STRERRNO(ENOPROTOOPT)
    CASE_STRERRNO(ENOSPC)
    CASE_STRERRNO(ENOSR)
    CASE_STRERRNO(ENOSTR)
    CASE_STRERRNO(ENOSYS)
    CASE_STRERRNO(ENOTBLK)
    CASE_STRERRNO(ENOTCONN)
    CASE_STRERRNO(ENOTDIR)
    CASE_STRERRNO(ENOTEMPTY)
    CASE_STRERRNO(ENOTRECOVERABLE)
    CASE_STRERRNO(ENOTSOCK)
    CASE_STRERRNO(ENOTSUP)
    CASE_STRERRNO(ENOTTY)
    CASE_STRERRNO(ENOTUNIQ)
    CASE_STRERRNO(ENXIO)
#if EOPNOTSUPP != ENOTSUP
    CASE_STRERRNO(EOPNOTSUPP)
#endif
    CASE_STRERRNO(EOVERFLOW)
    CASE_STRERRNO(EOWNERDEAD)
    CASE_STRERRNO(EPERM)
    CASE_STRERRNO(EPFNOSUPPORT)
    CASE_STRERRNO(EPIPE)
    CASE_STRERRNO(EPROTO)
    CASE_STRERRNO(EPROTONOSUPPORT)
    CASE_STRERRNO(EPROTOTYPE)
    CASE_STRERRNO(ERANGE)
    CASE_STRERRNO(EREMCHG)
    CASE_STRERRNO(EREMOTE)
    CASE_STRERRNO(EREMOTEIO)
    CASE_STRERRNO(ERESTART)
    CASE_STRERRNO(ERFKILL)
    CASE_STRERRNO(EROFS)
    CASE_STRERRNO(ESHUTDOWN)
    CASE_STRERRNO(ESPIPE)
    CASE_STRERRNO(ESOCKTNOSUPPORT)
    CASE_STRERRNO(ESRCH)
    CASE_STRERRNO(ESTALE)
    CASE_STRERRNO(ESTRPIPE)
    CASE_STRERRNO(ETIME)
    CASE_STRERRNO(ETIMEDOUT)
    CASE_STRERRNO(ETOOMANYREFS)
    CASE_STRERRNO(ETXTBSY)
    CASE_STRERRNO(EUCLEAN)
    CASE_STRERRNO(EUNATCH)
    CASE_STRERRNO(EUSERS)
#if EWOULDBLOCK != EAGAIN
    CASE_STRERRNO(EWOULDBLOCK)
#endif
    CASE_STRERRNO(EXDEV)
    CASE_STRERRNO(EXFULL)
    default:
        return "UNKNOWN";
    }
}
